import keymirror from 'keymirror';

export default keymirror({
  PAINT_INPUT_MADE: null,
  COLOR_PICKED: null,
  SET_CENTER: null,
  ADJUST_CANVAS_SCALE: null,
  START_CANVAS_LOADING: null,

  PAINT_INPUT_RECEIVED: null,
  PARTIAL_INITIAL_STATE_UPDATE: null,
  INITIAL_STATE_UPDATE: null,
  USER_COUNT_UPDATE: null,
  RANKING_UPDATE: null,

  GET_USER_INFO_REQUEST: null,
  GET_USER_INFO_SUCCESS: null,
  GET_USER_INFO_FAILURE: null,
  SET_USER_INFO: null,

  LOG_OUT_REQUEST: null,
  LOG_OUT_SUCCESS: null,
  AUTH_SUCCESS: null,
  AUTH_ERROR: null,
  AUTH_REQUEST: null,
  USER_INFO_SET: null,

  START_LOADING: null,
  STOP_LOADING: null,

  CLEAR_ALERT_MESSAGE: null,
  ALERT_MESSAGE: null,

  SET_USERNAME_REQUEST: null,
  SET_USERNAME_SUCCESS: null,
  SET_USERNAME_FAILURE: null,
  IS_USERNAME_AVAILABLE_REQUEST: null,
  IS_USERNAME_AVAILABLE_SUCCESS: null,
  IS_USERNAME_AVAILABLE_FAILURE: null,
});
